---
#Provision GitHub Enterprise
- hosts: localhost
  gather_facts: False

  vars_files:
  - group_vars/github

  tasks:
  - name: Launch AWS GHE Instance
    ec2:
     access_key: "{{ ec2_access_key }}"
     secret_key: "{{ ec2_secret_key }}"
     keypair: "{{ ec2_keypair }}"
     group: "{{ ec2_security_group }}"
     type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     region: "{{ ec2_region }}"
     instance_tags: "{'group':'{{ ec2_security_group }}','Name':'{{ server_type }}'}"
     count: "{{ ec2_instance_count }}"
     wait: true
     volumes:
       - volume_size: 10
         device_name: /dev/sdb
         device_type: gp2
         delete_on_termination: true
    register: ec2

  - name: Wait for Admin Port to come up (Port 8443)
    wait_for: host={{ item.public_dns_name }} port=8443 delay=60 timeout={{ aws_timeout }} state=started
    with_items: ec2.instances

  - name: Setup License and Admin Password
    local_action: command curl -L -X POST -k 'https://{{ ec2.instances[0].public_ip }}:8443/setup/api/start' -F license=@ghe-configuration/github-enterprise.ghl -F "password={{ mc_password }}"

  - name: Configure Instance Through JSON
    local_action: command curl -L -X PUT -k 'https://api_key:{{ mc_password }}@{{ ec2.instances[0].public_ip }}:8443/setup/api/settings' --data-urlencode "settings=`cat ghe-configuration/ghe-config.json`"

 # - name: Rerun Configure for Settings to Take Effect
 #   local_action: command curl -L -X POST -k 'https://api_key:{{ mc_password }}@{{ ec2.instances[0].public_ip }}:8443/setup/api/configure'

  - name: Wait for Configuration to complete.
    wait_for: curl -sik https://api_key:$ghepass@$ghehost:$gheport/setup/api/configcheck | grep 'status":"success' 
    
  - name: Creating first GitHub Enterprise administrator account
    local_action: command TEMPDIR=`mktemp -d /tmp/XXXXXXXXXXXXX`
  echo $TEMPDIR
  curl -isk https://$ghehost/join | grep 'Status: 200 OK'
  curl -k -v -L -c $TEMPDIR/cookies https://$ghehost/login > $TEMPDIR/github-curl.out
    authenticity_token=$(grep 'name="authenticity_token"' $TEMPDIR/github-curl.out | head -1 | sed -e 's/.*value="\([^"]*\)".*/\1/')
    curl -X POST -k -v -b $TEMPDIR/cookies -c $TEMPDIR/cookies \
    -F "authenticity_token=$authenticity_token" \
    -F "user[login]=octocat" \
    -F "user[email]=octocat@test" \
    -F "user[password]=$ghepass" \
    -F "user[password_confirmation]=$ghepass" \
    -F "source_label=Detail Form" \
    https://$ghehost/join >$TEMPDIR/github-curl.out 2>&1
    cat $TEMPDIR/github-curl.out
    grep "< Set-Cookie: logged_in=yes;" $TEMPDIR/github-curl.out
    rm -rf $TEMPDIR
